# Generated by Django 3.2.9 on 2021-11-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.TextField(help_text='Enter name of the paper')),
                ('authors', models.TextField(help_text='Enter names of authors of the paper')),
                ('conference', models.TextField(blank=True, default='NA', null=True)),
                ('rank', models.CharField(help_text='Rank of conference', max_length=2)),
                ('frequency', models.IntegerField(help_text='Number of times paper was fetched')),
            ],
        ),
    ]
