# Generated by Django 3.2.9 on 2021-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.TextField(help_text='Enter name of the paper')),
                ('authors', models.TextField(help_text='Enter names of authors of the paper')),
                ('conference', models.TextField(blank=True, default='NA', null=True)),
                ('rank', models.CharField(help_text='Rank of conference', max_length=2)),
            ],
            options={
                'ordering': ['rank', 'papername'],
            },
        ),
        migrations.AlterModelOptions(
            name='frequentpaper',
            options={'ordering': ['rank', 'papername']},
        ),
    ]
