# Generated by Django 3.2.9 on 2021-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0002_auto_20211103_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentpaper',
            name='authors',
            field=models.CharField(help_text='Enter names of authors of the paper', max_length=300),
        ),
        migrations.AlterField(
            model_name='frequentpaper',
            name='conference',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frequentpaper',
            name='papername',
            field=models.CharField(help_text='Enter name of the paper', max_length=300),
        ),
        migrations.AlterField(
            model_name='newpaper',
            name='authors',
            field=models.CharField(help_text='Enter names of authors of the paper', max_length=300),
        ),
        migrations.AlterField(
            model_name='newpaper',
            name='conference',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpaper',
            name='papername',
            field=models.CharField(help_text='Enter name of the paper', max_length=300),
        ),
    ]
