# Generated by Django 3.2.9 on 2021-11-08 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0003_auto_20211103_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpaper',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
