# Generated by Django 3.2.8 on 2021-11-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0003_auto_20211103_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='fetchinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(help_text='Enter name of the paper', max_length=500)),
                ('authors', models.CharField(help_text='Enter names of authors of the paper', max_length=500)),
                ('conference', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('rank', models.CharField(blank=True, default='NA', help_text='Rank of conference', max_length=2, null=True)),
                ('citations', models.IntegerField(default=0)),
                ('infcitations', models.IntegerField(default=0, help_text='Influential_citations')),
            ],
        ),
    ]
