# Generated by Django 3.2.8 on 2021-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0004_fetchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchinfo',
            name='keyword',
            field=models.CharField(default='NULL', help_text='keyword for search', max_length=100),
        ),
    ]
