# Generated by Django 3.2.8 on 2021-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0005_fetchinfo_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchinfo',
            name='paperid',
            field=models.CharField(default='NULL', help_text='hash of paper', max_length=100),
        ),
    ]
