# Generated by Django 3.2.8 on 2021-11-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0004_newpaper_date'),
        ('ranker', '0006_fetchinfo_paperid'),
    ]

    operations = [
    ]
