# Generated by Django 3.2.8 on 2021-11-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0007_merge_0004_newpaper_date_0006_fetchinfo_paperid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchinfo',
            name='access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fetchinfo',
            name='url',
            field=models.URLField(default='NA', null=True),
        ),
    ]
