# Generated by Django 3.2.8 on 2021-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0008_auto_20211108_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='conferencedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', help_text='conference name', max_length=100)),
                ('abbrv', models.CharField(default='NULL', help_text='abbreviation', max_length=10)),
                ('rank', models.CharField(default='NULL', help_text='abbreviation', max_length=3)),
                ('ptype', models.CharField(default='NULL', help_text='abbreviation', max_length=20)),
            ],
        ),
    ]
