# Generated by Django 3.2.8 on 2021-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0009_conferencedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencedata',
            name='abbrv',
            field=models.CharField(default='NULL', help_text='abbreviation', max_length=10, null=True),
        ),
    ]
