# Generated by Django 3.2.8 on 2021-11-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0011_mkeyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mkeyword',
            old_name='frequency',
            new_name='pages',
        ),
    ]
