# Generated by Django 3.2.8 on 2021-11-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0012_rename_frequency_mkeyword_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkeyword',
            name='frequency',
            field=models.IntegerField(default=1, help_text='frequency of keyword search'),
        ),
    ]
